source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 7.2"
gem "mysql2", "~> 0.5"
gem "puma", "~> 6.0"
gem "rack-cors", "~> 2.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug"
end

group :development do
  gem "rubocop", "~> 1.0", require: false
  gem "rubocop-rails", require: false
end
